title: Just Checking If This works or not
description: Dark Notes
baseurl: /new-random-web
url: https://SunilKumarPradhan.github.io/new-random-web

# Use remote_theme for GitHub Pages (theme: won't work)
remote_theme: just-the-docs

# Required plugins for GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: >-
  Made with ❤️ and sweaty fingers by <a href="https://github.com/SunilKumarPradhan">Sunil Kumar Pradhan</a> • Powered by <a href="https://github.com/SunilKumarPradhan/NoteSmith">NoteSmith</a>

aux_links:
  "View on GitHub": "https://github.com/SunilKumarPradhan/new-random-web"
  "Meet the Creator": "https://github.com/SunilKumarPradhan"